const nbaPlayers = [
  "LeBron James",
  "Kevin Durant",
  "Giannis Antetokounmpo",
  "Stephen Curry",
  "Nikola Jokic",
  "Joel Embiid",
  "James Harden",
  "Kawhi Leonard",
  "Damian Lillard",
  "Luka Doncic",
  "Jayson Tatum",
  "Ja Morant",
  "Donovan Mitchell",
  "Devin Booker",
  "Zach LaVine",
  "Trae Young",
  "Michael Porter Jr.",
  "Chet Holmgren",
  "Karl-Anthony Towns",
  "Zion Williamson",
  "Julius Randle",
  "Jordan Poole",
  "Bam Adebayo",
  "Jayson Tatum",
  "Pascal Siakam",
  "Jimmy Butler",
  "Collin Sexton",
  "Jalen Williams",
  "Kyrie Irving",
  "Klay Thompson",
  "Draymond Green",
  "Russell Westbrook",
  "Chris Paul",
  "Franz Wagner",
  "Scottie Barnes",
  "Tyrese Haliburton",
  "Alperen Sengun",
  "Victor Wembanyama",
  "Cam Thomas",
  "Dejounte Murray",
  "Jaren Jackson Jr.",
  "Paolo Banchero",
  "Cade Cunningham",
  "Anthony Edwards",
  "Jaylen Brown",
  "Tyrese Maxey",
  "De'Aaron Fox",
  "Jalen Brunson",
  "Shai Gilgeous-Alexander",
  "Brandon Ingram",
  "Terry Rozier",
  "Jalen Green",
  "Mikal Bridges",
  "Domantas Sabonis",
  "D'Angelo Russell",
  "Brandon Miller",
  "Austin Reaves",
  "Malik Monk",
  "Rudy Gobert",
  "Naz Reid",
  "Dillon Brooks",
  "Jrue Holiday",
  "Herbert Jones"
];

export default nbaPlayers