// const nbaPlayers = [
//   "LeBron James",
//   "Kevin Durant",
//   "Giannis Antetokounmpo",
//   "Stephen Curry",
//   "Nikola Jokic",
//   "Joel Embiid",
//   "James Harden",
//   "Kawhi Leonard",
//   "Damian Lillard",
//   "Luka Doncic",
//   "Jayson Tatum",
//   "Ja Morant",
//   "Donovan Mitchell",
//   "Devin Booker",
//   "Zach LaVine",
//   "Trae Young",
//   "Michael Porter Jr.",
//   "Chet Holmgren",
//   "Karl-Anthony Towns",
//   "Zion Williamson",
//   "Julius Randle",
//   "Jordan Poole",
//   "Bam Adebayo",
//   "Jayson Tatum",
//   "Pascal Siakam",
//   "Jimmy Butler",
//   "Collin Sexton",
//   "Jalen Williams",
//   "Kyrie Irving",
//   "Klay Thompson",
//   "Draymond Green",
//   "Russell Westbrook",
//   "Chris Paul",
//   "Franz Wagner",
//   "Scottie Barnes",
//   "Tyrese Haliburton",
//   "Alperen Sengun",
//   "Victor Wembanyama",
//   "Cam Thomas",
//   "Dejounte Murray",
//   "Jaren Jackson Jr.",
//   "Paolo Banchero",
//   "Cade Cunningham",
//   "Anthony Edwards",
//   "Jaylen Brown",
//   "Tyrese Maxey",
//   "De'Aaron Fox",
//   "Jalen Brunson",
//   "Shai Gilgeous-Alexander"
// ];


// const nbaTeams = [
//   "Atlanta Hawks",
//   "Boston Celtics",
//   "Brooklyn Nets",
//   "Charlotte Hornets",
//   "Chicago Bulls",
//   "Cleveland Cavaliers",
//   "Dallas Mavericks",
//   "Denver Nuggets",
//   "Detroit Pistons",
//   "Golden State Warriors",
//   "Houston Rockets",
//   "Indiana Pacers",
//   "Los Angeles Clippers",
//   "Los Angeles Lakers",
//   "Memphis Grizzlies",
//   "Miami Heat",
//   "Milwaukee Bucks",
//   "Minnesota Timberwolves",
//   "New Orleans Pelicans",
//   "New York Knicks",
//   "Oklahoma City Thunder",
//   "Orlando Magic",
//   "Philadelphia 76ers",
//   "Phoenix Suns",
//   "Portland Trail Blazers",
//   "Sacramento Kings",
//   "San Antonio Spurs",
//   "Toronto Raptors",
//   "Utah Jazz",
//   "Washington Wizards"
// ];